# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7291d1856d9a731c488b0a8dbb95006761c795f9f451c422e3298197b679cbe3b672539bd5b3abfc7dbcc0748aabd15f1cc0585b16aea67fa07b66d4c0946120

test:
  secret_key_base: 2c9bfbc9e9b90938a16f65cf478081634f48db1001e1b15dabac6f6408a23d4b24ef181c4ffd5c0fd873ce1bbff5c95a6675c052f961695c164e0c38a756b719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
